spring:
  cloud:
    function:
      definition: member_signin; nonmember_signin;  # Consumer 함수명
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        member_signin-in-0: # 채널 이름 (기본 규칙: 함수명-in-0)
          destination: bz_memberlog_request_member_signin # Topic 이름
          content-type: application/json
        nonmember_signin-in-0:
          destination: bz_memberlog_request_nonmember_signin
          content-type: application/json
---
spring:
  cloud:
    function:
      definition: member_signin; nonmember_signin;  # Consumer 함수명
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        member_signin-in-0: # 채널 이름 (기본 규칙: 함수명-in-0)
          destination: bz_memberlog_request_member_signin # Topic 이름
          content-type: application/json
        nonmember_signin-in-0:
          destination: bz_memberlog_request_nonmember_signin
          content-type: application/json
