services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      # MONGO_INITDB_DATABASE: notification
    volumes:
      - mongodb_datas:/data/db
volumes:
  mongodb_datas: