---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://admin:12345@localhost:27017/member_tracking?authSource=admin
      #auto-index-creation: true
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://admin:12345@localhost:27017/member_tracking?authSource=admin
      #auto-index-creation: true
